ens_jobeet_rest_job:
    type: rest
    resource: Ens\JobeetBundle\Controller\RestJobController
    name_prefix: ens_api_job_

#ens_jobeet_homepage:
#    path:     /
#    defaults: { _controller: EnsJobeetBundle:Job:index }

#EnsJobeetBundle_job:
#        resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
#        prefix:   /job