ens_jobeet_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /ens_job

ens_jobeet_homepage:
    path:     /
    defaults: { _controller: EnsJobeetBundle:Job:index }

EnsJobeetBundle_job:
        resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job

EnsJobeetBundle_category:
    pattern:  /category/{slug}/{page}
    defaults: { _controller: EnsJobeetBundle:Category:show, page: 1 }        
    